In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

In [4]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026

In [5]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [6]:
df.shape

(500, 9)

In [7]:
df.dtypes

Patient_ID            object
Gender                object
Age                    int64
Medical_Condition     object
Admission_Date        object
Admission_Type        object
Medical_Code          object
Billing_Amount       float64
Discharge_Date        object
dtype: object

In [8]:
df.isnull()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [11]:
df['Medical_Code'].isnull().sum()

np.int64(15)

In [17]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']

/tmp/ipykernel_585/4191176909.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Admission_Date']=pd.to_datetime(df['Admission_Date'])

0     2026-01-15
1     2026-01-16
2     2026-01-16
3     2026-01-17
4     2026-01-17
         ...
495   2026-09-20
496   2026-09-20
497   2026-09-21
498   2026-09-21
499   2026-09-22
Name: Admission_Date, Length: 500, dtype: datetime64[ns]

In [15]:
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

0     2026-01-20
1     2026-01-22
2     2026-01-18
3     2026-01-19
4     2026-01-25
         ...
495   2026-09-23
496   2026-09-24
497   2026-09-25
498   2026-09-23
499   2026-09-26
Name: Discharge_Date, Length: 500, dtype: datetime64[ns]

In [16]:
df['Admission_Type'].value_counts()

Admission_Type
Routine      196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [23]:
df['Admission_Type'] = (
    df['Admission_Type']
    .str.lower()
)

In [24]:
df.describe()

,Age,Admission_Date,Billing_Amount,Discharge_Date
count,500.000000,500,500.00000,500
mean,50.106000,2026-05-20 00:00:00,7249.00100,2026-05-22 17:51:21.600000
min,22.000000,2026-01-15 00:00:00,2300.00000,2026-01-18 00:00:00
25%,37.000000,2026-03-18 18:00:00,4400.00000,2026-03-20 18:00:00
50%,50.000000,2026-05-20 00:00:00,6950.00000,2026-05-22 12:00:00
75%,63.000000,2026-07-21 06:00:00,9400.00000,2026-07-24 06:00:00
max,78.000000,2026-09-22 00:00:00,14200.00000,2026-09-26 00:00:00
std,15.328035,NaN,3198.96932,NaN

In [ ]:
df["Admission"]

In [25]:
df["Hospital_Stay_Days"]=(df["Discharge_Date"]-df["Admission_Date"]).dt.days
df["Hospital_Stay_Days"].head()

0    5
1    6
2    2
3    2
4    8
Name: Hospital_Stay_Days, dtype: int64

In [26]:
df["Billing_Amount"].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64