In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [8]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [10]:
categorical_features = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

In [11]:
for col in categorical_features:
  df[col] = df[col].str.strip().str.title()

In [13]:
df[['gender','race/ethnicity',]]

     gender race/ethnicity
0    Female        Group B
1    Female        Group C
2    Female        Group B
3      Male        Group A
4      Male        Group C
..      ...            ...
995  Female        Group E
996    Male        Group C
997  Female        Group C
998  Female        Group D
999  Female        Group D

[1000 rows x 2 columns]

In [14]:
score_columms = [
    'math score',
    'reading score',
    'writing score'
]

In [17]:
print("\nStatistical Measures:")

for column in score_columms:
  print(f"\n{column}")
  print("Mean:",df[column].mean())
  print("Median:", df[column].median())
  print("Standard Deviation:", df[column].std())
  print("Q1:", df[column].quantile(0.25))
  print("Q2:", df[column].quantile(0.50))
  print("Q3:", df[column].quantile(0.75))

Statistical Measures:

math score
Mean: 66.089
Median: 66.0
Standard Deviation: 15.163080096009468
Q1: 57.0
Q2: 66.0
Q3: 77.0

reading score
Mean: 69.169
Median: 70.0
Standard Deviation: 14.60019193725222
Q1: 59.0
Q2: 70.0
Q3: 79.0

writing score
Mean: 68.054
Median: 69.0
Standard Deviation: 15.195657010869642
Q1: 57.75
Q2: 69.0
Q3: 79.0